// @generated by bolted-ffi-gen. DO NOT EDIT.
//
// Regenerate with `mise run gen:ffi`. `mise run check` fails if this file drifts from the
// declaration it was generated from (D22).
//
// This file is committed, and that is the design: BoltFFI's bindgen reads source text, so an FFI
// surface that does not exist as source does not exist at all -- silently. See
// docs/steps/artifacts/step-10-boltffi-visibility/.

//! The FFI layer of `Profile`, projected from `gen_profile`.
//!
//! Generated. Every judgement it appears to make is a call into `bolted-core`.
use crate::custom::*;
use ::bolted_core::Checked;
use ::bolted_core::report::ErrorData as CoreErrorData;
use ::bolted_core::{Draft, DraftId, Stashable, StoreDraft, SubmitError};
use ::bolted_ffi::*;
use ::gen_profile::*;
use boltffi::*;
use std::collections::BTreeMap;
use std::sync::{Arc, Mutex, MutexGuard};
/// Mirrors the core's field id. Declaration order, which is observable: a shell focusing the
/// first invalid field walks `dirty_fields()` in this order.
#[data]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProfileFieldId {
    Username,
    Name,
    Email,
    Availability,
}
fn to_field_id(f: ProfileField) -> ProfileFieldId {
    match f {
        ProfileField::Username => ProfileFieldId::Username,
        ProfileField::Name => ProfileFieldId::Name,
        ProfileField::Email => ProfileFieldId::Email,
        ProfileField::Availability => ProfileFieldId::Availability,
    }
}
fn to_core_field(f: ProfileFieldId) -> ProfileField {
    match f {
        ProfileFieldId::Username => ProfileField::Username,
        ProfileFieldId::Name => ProfileField::Name,
        ProfileFieldId::Email => ProfileField::Email,
        ProfileFieldId::Availability => ProfileField::Availability,
    }
}
/// The setter's typed refusal. `DraftClosed` is D23: the draft was submitted (C17) or closed
/// (C18), and a silent `Ok(())` would be a lie.
#[error]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum UsernameErrorFfi {
    TooShort { min: u32, actual: u32 },
    TooLong { max: u32, actual: u32 },
    InvalidChars,
    DraftClosed,
}
impl ::std::fmt::Display for UsernameErrorFfi {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, concat!("invalid username", ": {:?}"), self)
    }
}
impl ::std::error::Error for UsernameErrorFfi {}
impl ::core::convert::From<UnexpectedFfiCallbackError> for UsernameErrorFfi {
    fn from(_: UnexpectedFfiCallbackError) -> Self {
        UsernameErrorFfi::DraftClosed
    }
}
impl ::core::convert::From<UsernameError> for UsernameErrorFfi {
    fn from(e: UsernameError) -> Self {
        match e {
            UsernameError::TooShort { min, actual } => UsernameErrorFfi::TooShort { min, actual },
            UsernameError::TooLong { max, actual } => UsernameErrorFfi::TooLong { max, actual },
            UsernameError::InvalidChars => UsernameErrorFfi::InvalidChars,
        }
    }
}
/// The setter's typed refusal. `DraftClosed` is D23: the draft was submitted (C17) or closed
/// (C18), and a silent `Ok(())` would be a lie.
#[error]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum PersonNameErrorFfi {
    TooShort { min: u32, actual: u32 },
    TooLong { max: u32, actual: u32 },
    DraftClosed,
}
impl ::std::fmt::Display for PersonNameErrorFfi {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, concat!("invalid personname", ": {:?}"), self)
    }
}
impl ::std::error::Error for PersonNameErrorFfi {}
impl ::core::convert::From<UnexpectedFfiCallbackError> for PersonNameErrorFfi {
    fn from(_: UnexpectedFfiCallbackError) -> Self {
        PersonNameErrorFfi::DraftClosed
    }
}
impl ::core::convert::From<PersonNameError> for PersonNameErrorFfi {
    fn from(e: PersonNameError) -> Self {
        match e {
            PersonNameError::TooShort { min, actual } => {
                PersonNameErrorFfi::TooShort { min, actual }
            }
            PersonNameError::TooLong { max, actual } => PersonNameErrorFfi::TooLong { max, actual },
        }
    }
}
/// The setter's typed refusal. `DraftClosed` is D23: the draft was submitted (C17) or closed
/// (C18), and a silent `Ok(())` would be a lie.
#[error]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum EmailErrorFfi {
    Invalid,
    DraftClosed,
}
impl ::std::fmt::Display for EmailErrorFfi {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, concat!("invalid email", ": {:?}"), self)
    }
}
impl ::std::error::Error for EmailErrorFfi {}
impl ::core::convert::From<UnexpectedFfiCallbackError> for EmailErrorFfi {
    fn from(_: UnexpectedFfiCallbackError) -> Self {
        EmailErrorFfi::DraftClosed
    }
}
impl ::core::convert::From<EmailError> for EmailErrorFfi {
    fn from(e: EmailError) -> Self {
        match e {
            EmailError::Invalid => EmailErrorFfi::Invalid,
        }
    }
}
#[export]
pub trait UsernameChecker: Send + Sync {
    fn check(&self, value: String) -> CheckVerdictFfi;
}
/// One draft's whole observable state — the `observe` verb's item, and the store's canonical
/// stream item.
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProfileSnapshot {
    pub username: TextFieldState,
    pub name: TextFieldState,
    pub email: TextFieldState,
    pub availability: AvailabilityFieldState,
    /// The async check's observable sub-state, so a shell can render a spinner rather than
    /// infer one from a rule violation (step-02 finding 7).
    pub username_check: CheckStateFfi,
    pub any_dirty: bool,
    pub conflicts: Vec<ProfileFieldId>,
    pub status: DraftStatusFfi,
    /// The draft's `base_version`: a subscriber can version-stamp a `snapshot()`-then-
    /// `subscribe()` sequence and detect a missed event in the gap.
    pub version: u64,
}
/// Raw values for seeding or replacing the canonical entity. Each is validated through the
/// real value types — `apply_canonical` cannot install an invalid entity.
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProfileValues {
    pub username: String,
    pub name: String,
    pub email: String,
    pub availability: AvailabilityRaw,
}
/// The schema version this build stamps into every stash it writes, and gates on when it
/// restores one (D27). It travels *inside* the DTO, so the version a stash was written under
/// crosses process death with it and `restore` can refuse a stash from a schema this build
/// no longer accepts — a typed, wholesale refusal, not a silent `null`.
///
/// It is a fixed constant today. Deriving it from the declaration — so a tightened constraint
/// bumps it and old stashes refuse automatically — is D27's build-time `bolted-check`
/// constraint-semver event, and it is Phase 4's. The refusal *mechanism* does not wait for
/// that: it gates on whatever this constant holds.
pub const STASH_SCHEMA_VERSION: u32 = 1;
/// What a shell persists so an edit session survives process death (C20). Carries no `sync`
/// and no async verdict, on purpose: C13 + C16 then make a restored draft safe with no new
/// invariant. Carries its `schema_version` (D27): the envelope's version gate.
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProfileStashFfi {
    /// The `STASH_SCHEMA_VERSION` in force when this stash was written. `accept_stash` refuses
    /// a value this build does not recognise (D27) before any field is trusted.
    pub schema_version: u32,
    pub username: TextFieldStashFfi,
    pub name: TextFieldStashFfi,
    pub email: TextFieldStashFfi,
    pub availability: AvailabilityStash,
    pub base_version: u64,
    pub orphaned: bool,
}
/// A stash whose envelope this build has **accepted** (D27, parse-don't-validate). The only
/// way to obtain one is `accept_stash`, which gates the schema version; `restore` takes only
/// this, so an un-gated stash cannot be restored — the type system carries the proof.
///
/// (It is a distinct wrapper, not a fallible `restore`, because BoltFFI 0.27.3 cannot return
/// a class handle from a throwing method — see the step-12 upstream filing. Gating into a
/// `#[data]` token and restoring from it is the shape that fits the toolchain and is stronger
/// than a bypassable guard.)
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ProfileStashAcceptedFfi {
    pub stash: ProfileStashFfi,
}
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FieldErrorFfi {
    pub field: ProfileFieldId,
    pub error: ErrorData,
}
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuleViolationFfi {
    pub rule: String,
    pub pins: Vec<ProfileFieldId>,
    pub error: ErrorData,
}
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ValidationReportFfi {
    pub field_errors: Vec<FieldErrorFfi>,
    pub rule_errors: Vec<RuleViolationFfi>,
}
/// Mirrors `bolted_core::SubmitError`, plus the one failure an *id* can have that a draft
/// cannot: the foreign handle outlives the core-side draft, so it can submit twice.
#[error]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SubmitErrorFfi {
    Validation { report: ValidationReportFfi },
    Conflicted { fields: Vec<ProfileFieldId> },
    Orphaned,
    AlreadySubmitted,
}
impl ::std::fmt::Display for SubmitErrorFfi {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            SubmitErrorFfi::Validation { .. } => write!(f, "submit failed validation"),
            SubmitErrorFfi::Conflicted { .. } => write!(f, "submit blocked by conflicts"),
            SubmitErrorFfi::Orphaned => write!(f, "submit of an orphaned draft"),
            SubmitErrorFfi::AlreadySubmitted => write!(f, "draft already submitted"),
        }
    }
}
impl ::std::error::Error for SubmitErrorFfi {}
impl ::core::convert::From<UnexpectedFfiCallbackError> for SubmitErrorFfi {
    fn from(_: UnexpectedFfiCallbackError) -> Self {
        SubmitErrorFfi::AlreadySubmitted
    }
}
fn lock<T>(m: &Mutex<T>) -> MutexGuard<'_, T> {
    m.lock().unwrap_or_else(|poisoned| poisoned.into_inner())
}
/// A batch of stream emissions to flush AFTER the store lock is dropped.
type Emits = Vec<(Arc<StreamProducer<ProfileSnapshot>>, ProfileSnapshot)>;
fn flush(emits: Emits) {
    for (producer, snapshot) in emits {
        producer.push(snapshot);
    }
}
/// Everything the one `Mutex` protects. Canonical, versions, the draft registry, the rebase
/// bookkeeping and the submit path all live in `store` — none of it is written here (D16).
struct FfiState {
    store: ProfileStore,
    producers: BTreeMap<DraftId, Arc<StreamProducer<ProfileSnapshot>>>,
    store_producer: Arc<StreamProducer<ProfileSnapshot>>,
}
/// Give a freshly registered draft its own snapshot stream.
fn register_producer(
    g: &mut MutexGuard<'_, FfiState>,
    id: DraftId,
) -> Arc<StreamProducer<ProfileSnapshot>> {
    let producer = Arc::new(StreamProducer::new(256));
    g.producers.insert(id, producer.clone());
    producer
}
/// One snapshot per draft the core just moved, ready to flush **after** the lock is dropped.
fn draft_emits(g: &MutexGuard<'_, FfiState>, ids: &[DraftId]) -> Emits {
    ids.iter()
        .filter_map(|id| {
            let draft = g.store.draft(*id)?;
            let producer = g.producers.get(id)?;
            Some((producer.clone(), build_draft_snapshot(draft)))
        })
        .collect()
}
fn build_draft_snapshot(draft: &ProfileDraft) -> ProfileSnapshot {
    ProfileSnapshot {
        username: bolted_ffi::text_field_state(&draft.username),
        name: bolted_ffi::text_field_state(&draft.name),
        email: bolted_ffi::text_field_state(&draft.email),
        availability: crate::custom::availability_state(&draft.availability),
        username_check: bolted_ffi::check_state(draft.check_state(ProfileCheck::UsernameUnique)),
        any_dirty: !draft.dirty_fields().is_empty(),
        conflicts: draft.conflicts().into_iter().map(to_field_id).collect(),
        status: bolted_ffi::draft_status(draft.status()),
        version: draft.base_version(),
    }
}
/// The canonical entity as a snapshot.
///
/// A draft checked out of a canonical has exactly the shape a canonical snapshot needs: every
/// field `Valid` and `InSync`, nothing dirty, no conflicts, no check run. So it is built by
/// asking the core, rather than by a second hand-written table that could disagree with the
/// first. `spike-profile-ffi` wrote that table by hand, per field, twice.
fn canonical_snapshot(entity: &Profile, version: u64) -> ProfileSnapshot {
    build_draft_snapshot(&ProfileDraft::from_canonical(Some(entity), version))
}
/// An all-unset snapshot: what a tombstoned draft observes (C17, C18).
fn tombstone_snapshot() -> ProfileSnapshot {
    build_draft_snapshot(&ProfileDraft::from_canonical(None, 0))
}
fn to_stash_ffi(s: &ProfileStash) -> ProfileStashFfi {
    ProfileStashFfi {
        schema_version: STASH_SCHEMA_VERSION,
        username: bolted_ffi::text_stash(&s.username),
        name: bolted_ffi::text_stash(&s.name),
        email: bolted_ffi::text_stash(&s.email),
        availability: crate::custom::availability_stash(&s.availability),
        base_version: s.base_version,
        orphaned: s.orphaned,
    }
}
fn to_core_stash(s: &ProfileStashFfi) -> ProfileStash {
    ProfileStash {
        username: bolted_ffi::to_core_text_stash(&s.username),
        name: bolted_ffi::to_core_text_stash(&s.name),
        email: bolted_ffi::to_core_text_stash(&s.email),
        availability: crate::custom::availability_from_stash(&s.availability),
        base_version: s.base_version,
        orphaned: s.orphaned,
    }
}
/// The core's report is keyed by the *core* field id; the wire's is keyed by the `#[data]`
/// one. They are different types on purpose: only one of them can cross.
fn project_report(r: &::bolted_core::ValidationReport<ProfileField>) -> ValidationReportFfi {
    ValidationReportFfi {
        field_errors: r
            .field_errors
            .iter()
            .map(|(field, error)| FieldErrorFfi {
                field: to_field_id(*field),
                error: ErrorData::from(error.clone()),
            })
            .collect(),
        rule_errors: r
            .rule_errors
            .iter()
            .map(|v| RuleViolationFfi {
                rule: v.rule.to_string(),
                pins: v.pins.iter().map(|f| to_field_id(*f)).collect(),
                error: ErrorData::from(v.error.clone()),
            })
            .collect(),
    }
}
fn submit_error_to_dto(e: SubmitError<ProfileField>) -> SubmitErrorFfi {
    match e {
        SubmitError::Validation(report) => SubmitErrorFfi::Validation {
            report: project_report(&report),
        },
        SubmitError::Conflicted { fields } => SubmitErrorFfi::Conflicted {
            fields: fields.into_iter().map(to_field_id).collect(),
        },
        SubmitError::Orphaned => SubmitErrorFfi::Orphaned,
        SubmitError::AlreadySubmitted => SubmitErrorFfi::AlreadySubmitted,
    }
}
fn build_entity(v: ProfileValues) -> ::core::result::Result<Profile, ValidationReportFfi> {
    let username = <Username as ::bolted_core::Value>::try_new(v.username);
    let name = <PersonName as ::bolted_core::Value>::try_new(v.name);
    let email = <Email as ::bolted_core::Value>::try_new(v.email);
    let availability = <DateRange as ::bolted_core::Value>::try_new(
        crate::custom::availability_raw(v.availability),
    );
    match (username, name, email, availability) {
        (Ok(username), Ok(name), Ok(email), Ok(availability)) => Ok(Profile {
            username,
            name,
            email,
            availability,
        }),
        (username, name, email, availability) => {
            let mut field_errors = Vec::new();
            if let Err(e) = username {
                field_errors.push(FieldErrorFfi {
                    field: ProfileFieldId::Username,
                    error: bolted_ffi::error_data(e),
                });
            }
            if let Err(e) = name {
                field_errors.push(FieldErrorFfi {
                    field: ProfileFieldId::Name,
                    error: bolted_ffi::error_data(e),
                });
            }
            if let Err(e) = email {
                field_errors.push(FieldErrorFfi {
                    field: ProfileFieldId::Email,
                    error: bolted_ffi::error_data(e),
                });
            }
            if let Err(e) = availability {
                field_errors.push(FieldErrorFfi {
                    field: ProfileFieldId::Availability,
                    error: bolted_ffi::error_data(e),
                });
            }
            Err(ValidationReportFfi {
                field_errors,
                rule_errors: Vec::new(),
            })
        }
    }
}
pub struct ProfileStoreFfi {
    core: Arc<Mutex<FfiState>>,
}
impl Default for ProfileStoreFfi {
    fn default() -> Self {
        Self::new()
    }
}
#[export]
impl ProfileStoreFfi {
    pub fn new() -> ProfileStoreFfi {
        ProfileStoreFfi {
            core: Arc::new(Mutex::new(FfiState {
                store: ProfileStore::new(None),
                producers: BTreeMap::new(),
                store_producer: Arc::new(StreamProducer::new(256)),
            })),
        }
    }
    /// Set or replace the canonical entity. `Store::apply_canonical` does all of it and
    /// reports which drafts it moved.
    pub fn apply_canonical(
        &self,
        values: ProfileValues,
    ) -> ::core::result::Result<(), SubmitErrorFfi> {
        let entity =
            build_entity(values).map_err(|report| SubmitErrorFfi::Validation { report })?;
        let emits = {
            let mut g = lock(&self.core);
            let rebased = g.store.apply_canonical(entity.clone());
            let mut emits = draft_emits(&g, &rebased);
            emits.push((
                g.store_producer.clone(),
                canonical_snapshot(&entity, g.store.version()),
            ));
            emits
        };
        flush(emits);
        Ok(())
    }
    /// Check out a draft. Existing-canonical checkouts register for live rebase; create-flow
    /// checkouts do not (C12).
    pub fn checkout(&self) -> ProfileDraftFfi {
        let mut g = lock(&self.core);
        let id = g.store.checkout();
        let producer = register_producer(&mut g, id);
        ProfileDraftFfi {
            id,
            core: Arc::clone(&self.core),
            producer,
            username_checker: Mutex::new(None),
        }
    }
    /// D27, the parse gate. A stash is the first untrusted input in the system (bytes the OS
    /// held while we were dead, maybe written by an *older* build). `accept_stash` refuses a
    /// stash whose `schema_version` this build does not recognise — **wholesale** and typed,
    /// before any field is trusted — and otherwise hands back a #accepted the type system will
    /// let `restore` consume. The shell can tell a refusal from "no stash" (a typed error, not
    /// a silent `null`) and start a fresh session. Per-field degradation (C23) applies only
    /// *inside* an envelope that passed this gate.
    pub fn accept_stash(
        &self,
        stash: ProfileStashFfi,
    ) -> ::core::result::Result<ProfileStashAcceptedFfi, StashRefusedFfi> {
        if stash.schema_version != STASH_SCHEMA_VERSION {
            return Err(StashRefusedFfi::SchemaVersion {
                stashed: stash.schema_version,
                expected: STASH_SCHEMA_VERSION,
            });
        }
        Ok(ProfileStashAcceptedFfi { stash })
    }
    /// Restore a draft the shell stashed before its process was killed (C21). The rebase
    /// inside `Store::restore` is the point: a field whose canonical moved while the process
    /// was dead comes back **conflicted**, not silently dirty over a base it never saw.
    ///
    /// Takes only a #accepted, so a stash that never passed `accept_stash`'s version gate
    /// cannot reach here — parse-don't-validate carried in the type (D27).
    pub fn restore(&self, accepted: ProfileStashAcceptedFfi) -> ProfileDraftFfi {
        let mut g = lock(&self.core);
        let id = g.store.restore(&to_core_stash(&accepted.stash));
        let producer = register_producer(&mut g, id);
        ProfileDraftFfi {
            id,
            core: Arc::clone(&self.core),
            producer,
            username_checker: Mutex::new(None),
        }
    }
    /// Declared constraints for a field. Pure metadata, so it takes no lock. A shell derives
    /// `maxLength`, counters and required markers from THIS alone — no constraint literal in
    /// Swift or Kotlin.
    pub fn constraints(&self, field: ProfileFieldId) -> Vec<ConstraintFfi> {
        to_core_field(field)
            .constraints()
            .into_iter()
            .map(bolted_ffi::constraint)
            .collect()
    }
    /// Drafts that exist: checked out or restored, not yet submitted or closed.
    pub fn live_draft_count(&self) -> u32 {
        lock(&self.core).store.draft_count() as u32
    }
    /// Drafts the next canonical change would rebase: not create-flow (C12), not orphaned
    /// (C11). **Not** the same question as `live_draft_count` — see C22.
    pub fn rebasing_draft_count(&self) -> u32 {
        lock(&self.core).store.rebasing_draft_count() as u32
    }
    pub fn canonical(&self) -> Option<ProfileSnapshot> {
        let g = lock(&self.core);
        let version = g.store.version();
        g.store.canonical().map(|e| canonical_snapshot(e, version))
    }
    /// Handle round-trip identity: if BoltFFI passes the same Rust object back across the
    /// boundary, `store.same_draft(d) == d.id()`.
    pub fn same_draft(&self, other: &ProfileDraftFfi) -> u64 {
        other.id.as_u64()
    }
    /// A fresh canonical snapshot on every `apply_canonical` and every successful submit.
    #[ffi_stream(item = ProfileSnapshot)]
    pub fn snapshots(&self) -> Arc<EventSubscription<ProfileSnapshot>> {
        let producer = { lock(&self.core).store_producer.clone() };
        producer.subscribe()
    }
}
pub struct ProfileDraftFfi {
    id: DraftId,
    core: Arc<Mutex<FfiState>>,
    producer: Arc<StreamProducer<ProfileSnapshot>>,
    username_checker: Mutex<Option<Box<dyn UsernameChecker>>>,
}
#[export]
impl ProfileDraftFfi {
    /// Stable per-draft id.
    pub fn id(&self) -> u64 {
        self.id.as_u64()
    }
    /// `true` while the draft is present and un-submitted; `false` once submitted (C17) or
    /// closed (C18). **Ask this before you act**: it is the only total observer of a hazard
    /// the mutators now raise as `DraftClosed`.
    pub fn is_live(&self) -> bool {
        lock(&self.core).store.is_live(self.id)
    }
    pub fn try_set_username(&self, raw: String) -> ::core::result::Result<(), UsernameErrorFfi> {
        let (producer, snapshot, result) = {
            let mut g = lock(&self.core);
            let Some(draft) = g.store.draft_mut(self.id) else {
                return Err(UsernameErrorFfi::DraftClosed);
            };
            let result = draft.try_set_username(raw).map_err(UsernameErrorFfi::from);
            let snapshot = build_draft_snapshot(draft);
            (self.producer.clone(), snapshot, result)
        };
        producer.push(snapshot);
        result
    }
    pub fn try_set_name(&self, raw: String) -> ::core::result::Result<(), PersonNameErrorFfi> {
        let (producer, snapshot, result) = {
            let mut g = lock(&self.core);
            let Some(draft) = g.store.draft_mut(self.id) else {
                return Err(PersonNameErrorFfi::DraftClosed);
            };
            let result = draft.try_set_name(raw).map_err(PersonNameErrorFfi::from);
            let snapshot = build_draft_snapshot(draft);
            (self.producer.clone(), snapshot, result)
        };
        producer.push(snapshot);
        result
    }
    pub fn try_set_email(&self, raw: String) -> ::core::result::Result<(), EmailErrorFfi> {
        let (producer, snapshot, result) = {
            let mut g = lock(&self.core);
            let Some(draft) = g.store.draft_mut(self.id) else {
                return Err(EmailErrorFfi::DraftClosed);
            };
            let result = draft.try_set_email(raw).map_err(EmailErrorFfi::from);
            let snapshot = build_draft_snapshot(draft);
            (self.producer.clone(), snapshot, result)
        };
        producer.push(snapshot);
        result
    }
    pub fn try_set_availability(
        &self,
        raw: AvailabilityRaw,
    ) -> ::core::result::Result<(), AvailabilityErrorFfi> {
        let (producer, snapshot, result) = {
            let mut g = lock(&self.core);
            let Some(draft) = g.store.draft_mut(self.id) else {
                return Err(crate::custom::availability_closed());
            };
            let result = draft
                .try_set_availability(crate::custom::availability_raw(raw))
                .map_err(crate::custom::availability_error);
            let snapshot = build_draft_snapshot(draft);
            (self.producer.clone(), snapshot, result)
        };
        producer.push(snapshot);
        result
    }
    pub fn resolve_keep_mine(
        &self,
        field: ProfileFieldId,
    ) -> ::core::result::Result<(), DraftClosedFfi> {
        self.resolve(field, true)
    }
    pub fn resolve_take_theirs(
        &self,
        field: ProfileFieldId,
    ) -> ::core::result::Result<(), DraftClosedFfi> {
        self.resolve(field, false)
    }
    pub fn set_username_checker(&self, checker: Box<dyn UsernameChecker>) {
        *lock(&self.username_checker) = Some(checker);
    }
    /// Drive one single-flight check: begin (emit a `Pending` snapshot), call the foreign
    /// checker with **no lock held**, complete (emit the verdict). `Ok(false)` means no
    /// checker is set on a *live* draft; a released draft refuses (D23), checker or not.
    ///
    /// The core discards a superseded token, so a verdict that lands after the value moved is
    /// dropped rather than applied (C13).
    pub fn run_username_check(&self) -> ::core::result::Result<bool, DraftClosedFfi> {
        if lock(&self.core).store.draft_mut(self.id).is_none() {
            return Err(DraftClosedFfi::DraftClosed);
        }
        let Some(checker) = lock(&self.username_checker).take() else {
            return Ok(false);
        };
        let begun = {
            let mut g = lock(&self.core);
            g.store.draft_mut(self.id).map(|draft| {
                let value = bolted_ffi::text_of(&draft.username);
                let token = draft.begin_check(ProfileCheck::UsernameUnique);
                (token, value, build_draft_snapshot(draft))
            })
        };
        let Some((token, value, pending)) = begun else {
            *lock(&self.username_checker) = Some(checker);
            return Err(DraftClosedFfi::DraftClosed);
        };
        self.producer.push(pending);
        let verdict = checker.check(value);
        *lock(&self.username_checker) = Some(checker);
        let verdict: ::core::result::Result<(), CoreErrorData> = match verdict {
            CheckVerdictFfi::Pass => Ok(()),
            CheckVerdictFfi::Fail => Err(CoreErrorData::new("username_taken")),
        };
        let done = {
            let mut g = lock(&self.core);
            g.store.draft_mut(self.id).map(|draft| {
                let _superseded =
                    draft.complete_check(ProfileCheck::UsernameUnique, token, verdict);
                build_draft_snapshot(draft)
            })
        };
        match done {
            Some(snapshot) => {
                self.producer.push(snapshot);
                Ok(true)
            }
            None => Err(DraftClosedFfi::DraftClosed),
        }
    }
    /// Total: a tombstoned draft reports an empty report, not an error. A shell renders this
    /// on every keystroke and must never have to catch.
    pub fn validate(&self) -> ValidationReportFfi {
        let g = lock(&self.core);
        match g.store.draft(self.id) {
            Some(draft) => project_report(&draft.validate()),
            None => ValidationReportFfi {
                field_errors: Vec::new(),
                rule_errors: Vec::new(),
            },
        }
    }
    /// Commit this draft and adopt the result as the new canonical, rebasing every other
    /// registered draft. On success the draft is released and the handle becomes a tombstone
    /// (C17). On refusal it stays put under the same id: the edit session survives.
    pub fn submit(&self) -> ::core::result::Result<(), SubmitErrorFfi> {
        let emits = {
            let mut g = lock(&self.core);
            let rebased = g.store.submit(self.id).map_err(submit_error_to_dto)?;
            let mut emits = draft_emits(&g, &rebased);
            let version = g.store.version();
            if let Some(entity) = g.store.canonical() {
                emits.push((
                    g.store_producer.clone(),
                    canonical_snapshot(entity, version),
                ));
            }
            emits
        };
        flush(emits);
        Ok(())
    }
    /// Flatten to serializable data so the shell can persist it across process death (C20).
    pub fn stash(&self) -> ProfileStashFfi {
        let g = lock(&self.core);
        match g.store.draft(self.id) {
            Some(draft) => to_stash_ffi(&draft.stash()),
            None => to_stash_ffi(&ProfileDraft::from_canonical(None, 0).stash()),
        }
    }
    /// The draft's current state on demand — the recovery getter that makes drop-newest stream
    /// overflow non-fatal.
    pub fn snapshot(&self) -> ProfileSnapshot {
        let g = lock(&self.core);
        match g.store.draft(self.id) {
            Some(draft) => build_draft_snapshot(draft),
            None => tombstone_snapshot(),
        }
    }
    #[ffi_stream(item = ProfileSnapshot)]
    pub fn snapshots(&self) -> Arc<EventSubscription<ProfileSnapshot>> {
        self.producer.subscribe()
    }
    /// A deliberately tiny subscription, for exercising drop-newest overflow.
    #[ffi_stream(item = ProfileSnapshot)]
    pub fn snapshots_small(&self) -> Arc<EventSubscription<ProfileSnapshot>> {
        self.producer.subscribe_with_capacity(4)
    }
    fn resolve(
        &self,
        field: ProfileFieldId,
        keep_mine: bool,
    ) -> ::core::result::Result<(), DraftClosedFfi> {
        let (producer, snapshot) = {
            let mut g = lock(&self.core);
            let Some(draft) = g.store.draft_mut(self.id) else {
                return Err(DraftClosedFfi::DraftClosed);
            };
            let core_field = to_core_field(field);
            if keep_mine {
                draft.resolve_keep_mine(core_field);
            } else {
                draft.resolve_take_theirs(core_field);
            }
            (self.producer.clone(), build_draft_snapshot(draft))
        };
        producer.push(snapshot);
        Ok(())
    }
}
impl Drop for ProfileDraftFfi {
    /// Deinit-deregistration: when the foreign handle is released, `Drop` calls `Store::close`
    /// so `apply_canonical` stops rebasing a zombie. This is the *shell* calling close, not
    /// the framework doing it for free — exactly what C18 says. Kotlin's GC never runs it,
    /// which is why `AutoCloseable`/`onCleared()` are mandatory there.
    fn drop(&mut self) {
        let mut g = lock(&self.core);
        g.store.close(self.id);
        g.producers.remove(&self.id);
    }
}
