//! D28 / step 16: the committed constraint-surface snapshot is exactly what the declaration plus the
//! runtime `constraints()` produce. **Byte** equality — nothing formats a `.snap`, which is what
//! makes the comparison honest (as with the Kotlin/Swift codecs in `drift.rs`). The snapshot is
//! regenerated by `mise run gen:ffi`, never here.
//!
//! This is where the `DateRange` composite is covered: a source scan cannot see its
//! `Constraint::Custom("start_le_end")` (D20), but `ProfileField::Availability.constraints()` — run
//! here, against the linked feature — does, and the renderer's field-coverage cross-check refuses a
//! surface that drops it.
//!
//! The runtime surface below is built the same way `examples/gen-constraints.rs` builds it — kept in
//! step by this very check: if the two disagreed, either the render would not match the committed
//! file, or a missing field would be a `RenderError`. Both are a red test.

use bolted_check::{RuntimeField, RuntimeSurface, render_constraint_snapshot};
use bolted_decl::Feature;
use gen_profile::ProfileField;

const DUTY: &str = "the constraint surface changed — review the diff, decide whether \
     STASH_SCHEMA_VERSION must move (D27: a tightening strands stashed drafts), then \
     `mise run gen:ffi`.";

#[test]
fn the_committed_constraint_snapshot_matches_the_surface() {
    let source = include_str!("../../gen-profile/src/lib.rs");
    let feature = Feature::from_file(&syn::parse_file(source).expect("gen-profile source parses"))
        .expect("gen-profile scans");
    let runtime = RuntimeSurface {
        schema_version: gen_profile_ffi::STASH_SCHEMA_VERSION,
        fields: vec![
            RuntimeField::new("username", ProfileField::Username.constraints()),
            RuntimeField::new("name", ProfileField::Name.constraints()),
            RuntimeField::new("email", ProfileField::Email.constraints()),
            RuntimeField::new("availability", ProfileField::Availability.constraints()),
        ],
    };
    let rendered = render_constraint_snapshot("gen-profile", &feature, &runtime)
        .expect("runtime surface covers the declaration");
    let committed = include_str!("../../gen-profile/constraints.snap");
    if rendered != committed {
        panic!("{}", first_diff(&rendered, committed));
    }
}

/// The first differing line, named, followed by the D27 duty. Mirrors the first-diff message the FFI
/// drift checks print (`bolted_ffi_gen::check_drift`).
fn first_diff(rendered: &str, committed: &str) -> String {
    for (i, (r, c)) in rendered.lines().zip(committed.lines()).enumerate() {
        if r != c {
            return format!(
                "constraint-surface snapshot drift at line {}:\n  committed: {c}\n  rendered:  {r}\n\n{DUTY}",
                i + 1
            );
        }
    }
    format!(
        "constraint-surface snapshot length drift: {} committed lines, {} rendered\n\n{DUTY}",
        committed.lines().count(),
        rendered.lines().count()
    )
}
