// @generated by bolted-ffi-gen. DO NOT EDIT.
//
// Regenerate with `mise run gen:ffi`. `mise run check` fails if this file drifts from the
// declaration it was generated from (D22).
//
// This file is committed, and that is the design: BoltFFI's bindgen reads source text, so an FFI
// surface that does not exist as source does not exist at all -- silently. See
// docs/steps/artifacts/step-10-boltffi-visibility/.

//! The FFI layer of `Note`, projected from `gen_note`.
//!
//! Generated. Every judgement it appears to make is a call into `bolted-core`.
use ::bolted_core::{Draft, DraftId, Stashable, StoreDraft, SubmitError};
use ::bolted_ffi::*;
use ::gen_note::*;
use boltffi::*;
use std::collections::BTreeMap;
use std::sync::{Arc, Mutex, MutexGuard};
/// Mirrors the core's field id. Declaration order, which is observable: a shell focusing the
/// first invalid field walks `dirty_fields()` in this order.
#[data]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum NoteFieldId {
    Title,
    Body,
}
fn to_field_id(f: NoteField) -> NoteFieldId {
    match f {
        NoteField::Title => NoteFieldId::Title,
        NoteField::Body => NoteFieldId::Body,
    }
}
fn to_core_field(f: NoteFieldId) -> NoteField {
    match f {
        NoteFieldId::Title => NoteField::Title,
        NoteFieldId::Body => NoteField::Body,
    }
}
/// The setter's typed refusal. `DraftClosed` is D23: the draft was submitted (C17) or closed
/// (C18), and a silent `Ok(())` would be a lie.
#[error]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum TitleErrorFfi {
    TooShort { min: u32, actual: u32 },
    TooLong { max: u32, actual: u32 },
    DraftClosed,
}
impl ::std::fmt::Display for TitleErrorFfi {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, concat!("invalid title", ": {:?}"), self)
    }
}
impl ::std::error::Error for TitleErrorFfi {}
impl ::core::convert::From<UnexpectedFfiCallbackError> for TitleErrorFfi {
    fn from(_: UnexpectedFfiCallbackError) -> Self {
        TitleErrorFfi::DraftClosed
    }
}
impl ::core::convert::From<TitleError> for TitleErrorFfi {
    fn from(e: TitleError) -> Self {
        match e {
            TitleError::TooShort { min, actual } => TitleErrorFfi::TooShort { min, actual },
            TitleError::TooLong { max, actual } => TitleErrorFfi::TooLong { max, actual },
        }
    }
}
/// The setter's typed refusal. `DraftClosed` is D23: the draft was submitted (C17) or closed
/// (C18), and a silent `Ok(())` would be a lie.
#[error]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum BodyErrorFfi {
    TooShort { min: u32, actual: u32 },
    TooLong { max: u32, actual: u32 },
    DraftClosed,
}
impl ::std::fmt::Display for BodyErrorFfi {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        write!(f, concat!("invalid body", ": {:?}"), self)
    }
}
impl ::std::error::Error for BodyErrorFfi {}
impl ::core::convert::From<UnexpectedFfiCallbackError> for BodyErrorFfi {
    fn from(_: UnexpectedFfiCallbackError) -> Self {
        BodyErrorFfi::DraftClosed
    }
}
impl ::core::convert::From<BodyError> for BodyErrorFfi {
    fn from(e: BodyError) -> Self {
        match e {
            BodyError::TooShort { min, actual } => BodyErrorFfi::TooShort { min, actual },
            BodyError::TooLong { max, actual } => BodyErrorFfi::TooLong { max, actual },
        }
    }
}
/// One draft's whole observable state — the `observe` verb's item, and the store's canonical
/// stream item.
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NoteSnapshot {
    pub title: TextFieldState,
    pub body: TextFieldState,
    pub any_dirty: bool,
    pub conflicts: Vec<NoteFieldId>,
    pub status: DraftStatusFfi,
    /// The draft's `base_version`: a subscriber can version-stamp a `snapshot()`-then-
    /// `subscribe()` sequence and detect a missed event in the gap.
    pub version: u64,
}
/// Raw values for seeding or replacing the canonical entity. Each is validated through the
/// real value types — `apply_canonical` cannot install an invalid entity.
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NoteValues {
    pub title: String,
    pub body: String,
}
/// What a shell persists so an edit session survives process death (C20). Carries no `sync`
/// and no async verdict, on purpose: C13 + C16 then make a restored draft safe with no new
/// invariant.
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct NoteStashFfi {
    pub title: TextFieldStashFfi,
    pub body: TextFieldStashFfi,
    pub base_version: u64,
    pub orphaned: bool,
}
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct FieldErrorFfi {
    pub field: NoteFieldId,
    pub error: ErrorData,
}
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct RuleViolationFfi {
    pub rule: String,
    pub pins: Vec<NoteFieldId>,
    pub error: ErrorData,
}
#[data]
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ValidationReportFfi {
    pub field_errors: Vec<FieldErrorFfi>,
    pub rule_errors: Vec<RuleViolationFfi>,
}
/// Mirrors `bolted_core::SubmitError`, plus the one failure an *id* can have that a draft
/// cannot: the foreign handle outlives the core-side draft, so it can submit twice.
#[error]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SubmitErrorFfi {
    Validation { report: ValidationReportFfi },
    Conflicted { fields: Vec<NoteFieldId> },
    Orphaned,
    AlreadySubmitted,
}
impl ::std::fmt::Display for SubmitErrorFfi {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match self {
            SubmitErrorFfi::Validation { .. } => write!(f, "submit failed validation"),
            SubmitErrorFfi::Conflicted { .. } => write!(f, "submit blocked by conflicts"),
            SubmitErrorFfi::Orphaned => write!(f, "submit of an orphaned draft"),
            SubmitErrorFfi::AlreadySubmitted => write!(f, "draft already submitted"),
        }
    }
}
impl ::std::error::Error for SubmitErrorFfi {}
impl ::core::convert::From<UnexpectedFfiCallbackError> for SubmitErrorFfi {
    fn from(_: UnexpectedFfiCallbackError) -> Self {
        SubmitErrorFfi::AlreadySubmitted
    }
}
fn lock<T>(m: &Mutex<T>) -> MutexGuard<'_, T> {
    m.lock().unwrap_or_else(|poisoned| poisoned.into_inner())
}
/// A batch of stream emissions to flush AFTER the store lock is dropped.
type Emits = Vec<(Arc<StreamProducer<NoteSnapshot>>, NoteSnapshot)>;
fn flush(emits: Emits) {
    for (producer, snapshot) in emits {
        producer.push(snapshot);
    }
}
/// Everything the one `Mutex` protects. Canonical, versions, the draft registry, the rebase
/// bookkeeping and the submit path all live in `store` — none of it is written here (D16).
struct FfiState {
    store: NoteStore,
    producers: BTreeMap<DraftId, Arc<StreamProducer<NoteSnapshot>>>,
    store_producer: Arc<StreamProducer<NoteSnapshot>>,
}
/// Give a freshly registered draft its own snapshot stream.
fn register_producer(
    g: &mut MutexGuard<'_, FfiState>,
    id: DraftId,
) -> Arc<StreamProducer<NoteSnapshot>> {
    let producer = Arc::new(StreamProducer::new(256));
    g.producers.insert(id, producer.clone());
    producer
}
/// One snapshot per draft the core just moved, ready to flush **after** the lock is dropped.
fn draft_emits(g: &MutexGuard<'_, FfiState>, ids: &[DraftId]) -> Emits {
    ids.iter()
        .filter_map(|id| {
            let draft = g.store.draft(*id)?;
            let producer = g.producers.get(id)?;
            Some((producer.clone(), build_draft_snapshot(draft)))
        })
        .collect()
}
fn build_draft_snapshot(draft: &NoteDraft) -> NoteSnapshot {
    NoteSnapshot {
        title: bolted_ffi::text_field_state(&draft.title),
        body: bolted_ffi::text_field_state(&draft.body),
        any_dirty: !draft.dirty_fields().is_empty(),
        conflicts: draft.conflicts().into_iter().map(to_field_id).collect(),
        status: bolted_ffi::draft_status(draft.status()),
        version: draft.base_version(),
    }
}
/// The canonical entity as a snapshot.
///
/// A draft checked out of a canonical has exactly the shape a canonical snapshot needs: every
/// field `Valid` and `InSync`, nothing dirty, no conflicts, no check run. So it is built by
/// asking the core, rather than by a second hand-written table that could disagree with the
/// first. `spike-profile-ffi` wrote that table by hand, per field, twice.
fn canonical_snapshot(entity: &Note, version: u64) -> NoteSnapshot {
    build_draft_snapshot(&NoteDraft::from_canonical(Some(entity), version))
}
/// An all-unset snapshot: what a tombstoned draft observes (C17, C18).
fn tombstone_snapshot() -> NoteSnapshot {
    build_draft_snapshot(&NoteDraft::from_canonical(None, 0))
}
fn to_stash_ffi(s: &NoteStash) -> NoteStashFfi {
    NoteStashFfi {
        title: bolted_ffi::text_stash(&s.title),
        body: bolted_ffi::text_stash(&s.body),
        base_version: s.base_version,
        orphaned: s.orphaned,
    }
}
fn to_core_stash(s: &NoteStashFfi) -> NoteStash {
    NoteStash {
        title: bolted_ffi::to_core_text_stash(&s.title),
        body: bolted_ffi::to_core_text_stash(&s.body),
        base_version: s.base_version,
        orphaned: s.orphaned,
    }
}
/// The core's report is keyed by the *core* field id; the wire's is keyed by the `#[data]`
/// one. They are different types on purpose: only one of them can cross.
fn project_report(r: &::bolted_core::ValidationReport<NoteField>) -> ValidationReportFfi {
    ValidationReportFfi {
        field_errors: r
            .field_errors
            .iter()
            .map(|(field, error)| FieldErrorFfi {
                field: to_field_id(*field),
                error: ErrorData::from(error.clone()),
            })
            .collect(),
        rule_errors: r
            .rule_errors
            .iter()
            .map(|v| RuleViolationFfi {
                rule: v.rule.to_string(),
                pins: v.pins.iter().map(|f| to_field_id(*f)).collect(),
                error: ErrorData::from(v.error.clone()),
            })
            .collect(),
    }
}
fn submit_error_to_dto(e: SubmitError<NoteField>) -> SubmitErrorFfi {
    match e {
        SubmitError::Validation(report) => SubmitErrorFfi::Validation {
            report: project_report(&report),
        },
        SubmitError::Conflicted { fields } => SubmitErrorFfi::Conflicted {
            fields: fields.into_iter().map(to_field_id).collect(),
        },
        SubmitError::Orphaned => SubmitErrorFfi::Orphaned,
        SubmitError::AlreadySubmitted => SubmitErrorFfi::AlreadySubmitted,
    }
}
fn build_entity(v: NoteValues) -> ::core::result::Result<Note, ValidationReportFfi> {
    let title = <Title as ::bolted_core::Value>::try_new(v.title);
    let body = <Body as ::bolted_core::Value>::try_new(v.body);
    match (title, body) {
        (Ok(title), Ok(body)) => Ok(Note { title, body }),
        (title, body) => {
            let mut field_errors = Vec::new();
            if let Err(e) = title {
                field_errors.push(FieldErrorFfi {
                    field: NoteFieldId::Title,
                    error: bolted_ffi::error_data(e),
                });
            }
            if let Err(e) = body {
                field_errors.push(FieldErrorFfi {
                    field: NoteFieldId::Body,
                    error: bolted_ffi::error_data(e),
                });
            }
            Err(ValidationReportFfi {
                field_errors,
                rule_errors: Vec::new(),
            })
        }
    }
}
pub struct NoteStoreFfi {
    core: Arc<Mutex<FfiState>>,
}
impl Default for NoteStoreFfi {
    fn default() -> Self {
        Self::new()
    }
}
#[export]
impl NoteStoreFfi {
    pub fn new() -> NoteStoreFfi {
        NoteStoreFfi {
            core: Arc::new(Mutex::new(FfiState {
                store: NoteStore::new(None),
                producers: BTreeMap::new(),
                store_producer: Arc::new(StreamProducer::new(256)),
            })),
        }
    }
    /// Set or replace the canonical entity. `Store::apply_canonical` does all of it and
    /// reports which drafts it moved.
    pub fn apply_canonical(
        &self,
        values: NoteValues,
    ) -> ::core::result::Result<(), SubmitErrorFfi> {
        let entity =
            build_entity(values).map_err(|report| SubmitErrorFfi::Validation { report })?;
        let emits = {
            let mut g = lock(&self.core);
            let rebased = g.store.apply_canonical(entity.clone());
            let mut emits = draft_emits(&g, &rebased);
            emits.push((
                g.store_producer.clone(),
                canonical_snapshot(&entity, g.store.version()),
            ));
            emits
        };
        flush(emits);
        Ok(())
    }
    /// Check out a draft. Existing-canonical checkouts register for live rebase; create-flow
    /// checkouts do not (C12).
    pub fn checkout(&self) -> NoteDraftFfi {
        let mut g = lock(&self.core);
        let id = g.store.checkout();
        let producer = register_producer(&mut g, id);
        NoteDraftFfi {
            id,
            core: Arc::clone(&self.core),
            producer,
        }
    }
    /// Restore a draft the shell stashed before its process was killed (C21). The rebase
    /// inside `Store::restore` is the point: a field whose canonical moved while the process
    /// was dead comes back **conflicted**, not silently dirty over a base it never saw.
    pub fn restore(&self, stash: NoteStashFfi) -> NoteDraftFfi {
        let mut g = lock(&self.core);
        let id = g.store.restore(&to_core_stash(&stash));
        let producer = register_producer(&mut g, id);
        NoteDraftFfi {
            id,
            core: Arc::clone(&self.core),
            producer,
        }
    }
    /// Declared constraints for a field. Pure metadata, so it takes no lock. A shell derives
    /// `maxLength`, counters and required markers from THIS alone — no constraint literal in
    /// Swift or Kotlin.
    pub fn constraints(&self, field: NoteFieldId) -> Vec<ConstraintFfi> {
        to_core_field(field)
            .constraints()
            .into_iter()
            .map(bolted_ffi::constraint)
            .collect()
    }
    /// Drafts that exist: checked out or restored, not yet submitted or closed.
    pub fn live_draft_count(&self) -> u32 {
        lock(&self.core).store.draft_count() as u32
    }
    /// Drafts the next canonical change would rebase: not create-flow (C12), not orphaned
    /// (C11). **Not** the same question as `live_draft_count` — see C22.
    pub fn rebasing_draft_count(&self) -> u32 {
        lock(&self.core).store.rebasing_draft_count() as u32
    }
    pub fn canonical(&self) -> Option<NoteSnapshot> {
        let g = lock(&self.core);
        let version = g.store.version();
        g.store.canonical().map(|e| canonical_snapshot(e, version))
    }
    /// Handle round-trip identity: if BoltFFI passes the same Rust object back across the
    /// boundary, `store.same_draft(d) == d.id()`.
    pub fn same_draft(&self, other: &NoteDraftFfi) -> u64 {
        other.id.as_u64()
    }
    /// A fresh canonical snapshot on every `apply_canonical` and every successful submit.
    #[ffi_stream(item = NoteSnapshot)]
    pub fn snapshots(&self) -> Arc<EventSubscription<NoteSnapshot>> {
        let producer = { lock(&self.core).store_producer.clone() };
        producer.subscribe()
    }
}
pub struct NoteDraftFfi {
    id: DraftId,
    core: Arc<Mutex<FfiState>>,
    producer: Arc<StreamProducer<NoteSnapshot>>,
}
#[export]
impl NoteDraftFfi {
    /// Stable per-draft id.
    pub fn id(&self) -> u64 {
        self.id.as_u64()
    }
    /// `true` while the draft is present and un-submitted; `false` once submitted (C17) or
    /// closed (C18). **Ask this before you act**: it is the only total observer of a hazard
    /// the mutators now raise as `DraftClosed`.
    pub fn is_live(&self) -> bool {
        lock(&self.core).store.is_live(self.id)
    }
    pub fn try_set_title(&self, value: String) -> ::core::result::Result<(), TitleErrorFfi> {
        let (producer, snapshot, result) = {
            let mut g = lock(&self.core);
            let Some(draft) = g.store.draft_mut(self.id) else {
                return Err(TitleErrorFfi::DraftClosed);
            };
            let result = draft.try_set_title(value).map_err(TitleErrorFfi::from);
            let snapshot = build_draft_snapshot(draft);
            (self.producer.clone(), snapshot, result)
        };
        producer.push(snapshot);
        result
    }
    pub fn try_set_body(&self, value: String) -> ::core::result::Result<(), BodyErrorFfi> {
        let (producer, snapshot, result) = {
            let mut g = lock(&self.core);
            let Some(draft) = g.store.draft_mut(self.id) else {
                return Err(BodyErrorFfi::DraftClosed);
            };
            let result = draft.try_set_body(value).map_err(BodyErrorFfi::from);
            let snapshot = build_draft_snapshot(draft);
            (self.producer.clone(), snapshot, result)
        };
        producer.push(snapshot);
        result
    }
    pub fn resolve_keep_mine(
        &self,
        field: NoteFieldId,
    ) -> ::core::result::Result<(), DraftClosedFfi> {
        self.resolve(field, true)
    }
    pub fn resolve_take_theirs(
        &self,
        field: NoteFieldId,
    ) -> ::core::result::Result<(), DraftClosedFfi> {
        self.resolve(field, false)
    }
    /// Total: a tombstoned draft reports an empty report, not an error. A shell renders this
    /// on every keystroke and must never have to catch.
    pub fn validate(&self) -> ValidationReportFfi {
        let g = lock(&self.core);
        match g.store.draft(self.id) {
            Some(draft) => project_report(&draft.validate()),
            None => ValidationReportFfi {
                field_errors: Vec::new(),
                rule_errors: Vec::new(),
            },
        }
    }
    /// Commit this draft and adopt the result as the new canonical, rebasing every other
    /// registered draft. On success the draft is released and the handle becomes a tombstone
    /// (C17). On refusal it stays put under the same id: the edit session survives.
    pub fn submit(&self) -> ::core::result::Result<(), SubmitErrorFfi> {
        let emits = {
            let mut g = lock(&self.core);
            let rebased = g.store.submit(self.id).map_err(submit_error_to_dto)?;
            let mut emits = draft_emits(&g, &rebased);
            let version = g.store.version();
            if let Some(entity) = g.store.canonical() {
                emits.push((
                    g.store_producer.clone(),
                    canonical_snapshot(entity, version),
                ));
            }
            emits
        };
        flush(emits);
        Ok(())
    }
    /// Flatten to serializable data so the shell can persist it across process death (C20).
    pub fn stash(&self) -> NoteStashFfi {
        let g = lock(&self.core);
        match g.store.draft(self.id) {
            Some(draft) => to_stash_ffi(&draft.stash()),
            None => to_stash_ffi(&NoteDraft::from_canonical(None, 0).stash()),
        }
    }
    /// The draft's current state on demand — the recovery getter that makes drop-newest stream
    /// overflow non-fatal.
    pub fn snapshot(&self) -> NoteSnapshot {
        let g = lock(&self.core);
        match g.store.draft(self.id) {
            Some(draft) => build_draft_snapshot(draft),
            None => tombstone_snapshot(),
        }
    }
    #[ffi_stream(item = NoteSnapshot)]
    pub fn snapshots(&self) -> Arc<EventSubscription<NoteSnapshot>> {
        self.producer.subscribe()
    }
    /// A deliberately tiny subscription, for exercising drop-newest overflow.
    #[ffi_stream(item = NoteSnapshot)]
    pub fn snapshots_small(&self) -> Arc<EventSubscription<NoteSnapshot>> {
        self.producer.subscribe_with_capacity(4)
    }
    fn resolve(
        &self,
        field: NoteFieldId,
        keep_mine: bool,
    ) -> ::core::result::Result<(), DraftClosedFfi> {
        let (producer, snapshot) = {
            let mut g = lock(&self.core);
            let Some(draft) = g.store.draft_mut(self.id) else {
                return Err(DraftClosedFfi::DraftClosed);
            };
            let core_field = to_core_field(field);
            if keep_mine {
                draft.resolve_keep_mine(core_field);
            } else {
                draft.resolve_take_theirs(core_field);
            }
            (self.producer.clone(), build_draft_snapshot(draft))
        };
        producer.push(snapshot);
        Ok(())
    }
}
impl Drop for NoteDraftFfi {
    /// Deinit-deregistration: when the foreign handle is released, `Drop` calls `Store::close`
    /// so `apply_canonical` stops rebasing a zombie. This is the *shell* calling close, not
    /// the framework doing it for free — exactly what C18 says. Kotlin's GC never runs it,
    /// which is why `AutoCloseable`/`onCleared()` are mandatory there.
    fn drop(&mut self) {
        let mut g = lock(&self.core);
        g.store.close(self.id);
        g.producers.remove(&self.id);
    }
}
