//! `bolted-ffi-gen` — the FFI layer, emitted as Rust source text (D22).
//!
//! ## Why this is not a proc macro
//!
//! BoltFFI discovers its FFI surface by reading source files off disk and parsing them with `syn`
//! (`boltffi_scan::SourceTree::load`). It never sees expanded code, not even under its own
//! `BINDING_EXPANSION` mode, which re-scans the same file. A `#[data]` struct emitted by a macro is
//! **silently absent** from the generated Swift, and `boltffi generate` exits 0.
//!
//! `docs/steps/artifacts/step-10-boltffi-visibility/probe.sh` builds that table from scratch. It is
//! why `#[bolted::feature_model]` could never have existed, and why D21 cut it for the wrong reason.
//!
//! ## What replaces it
//!
//! `mise run gen:ffi` writes `crates/<feature>-ffi/src/generated.rs`. `mise run check` regenerates it
//! in memory and byte-compares. The generated file is committed, formatted, and read in review — which
//! is strictly better than a macro expansion nobody reads, given §5's own verdict that macro output is
//! the least-verifiable code on the ladder.
//!
//! Generation is pure: source text in, source text out. It needs no boltffi CLI, no Xcode, no NDK, so
//! the drift check lives inside `mise run check` where every other invariant does.

use bolted_decl::Feature;
use bolted_decl::naming::suffixed;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;

mod dto;
mod field;
mod wrapper;

#[cfg(test)]
mod golden;

/// The banner. `prettyplease` formats an AST and cannot carry comments, so it is prepended to the
/// formatted text rather than emitted as tokens.
const BANNER: &str = "\
// @generated by bolted-ffi-gen. DO NOT EDIT.
//
// Regenerate with `mise run gen:ffi`. `mise run check` fails if this file drifts from the
// declaration it was generated from (D22).
//
// This file is committed, and that is the design: BoltFFI's bindgen reads source text, so an FFI
// surface that does not exist as source does not exist at all -- silently. See
// docs/steps/artifacts/step-10-boltffi-visibility/.

";

/// Generate the FFI layer for the feature declared in `source`.
///
/// `feature_crate` is the Rust name of the crate that source belongs to (`gen_profile`), which the
/// generated code globs in order to name the entity, draft, store and value types.
pub fn generate(source: &str, feature_crate: &str) -> syn::Result<String> {
    let file = syn::parse_file(source)?;
    let feature = Feature::from_file(&file)?;
    let tokens = emit(&feature, feature_crate)?;
    let parsed: syn::File = syn::parse2(tokens)?;
    reject_reserved_type_names(&parsed)?;
    Ok(format!("{BANNER}{}", prettyplease::unparse(&parsed)))
}

/// Type names a generated foreign type must not shadow, per language. Not exhaustive — the
/// high-traffic Foundation/stdlib names whose collision is silent and confusing (`Date` meaning
/// "our Date" in one file and `Foundation.Date` in the next). `Error` earns its place on both:
/// Swift's `Error` protocol and Kotlin's `Error` class.
const SWIFT_RESERVED: &[&str] = &[
    "Date", "URL", "Data", "Error", "Result", "Task", "Array", "Set", "String", "Optional",
];
const KOTLIN_RESERVED: &[&str] = &[
    "Error",
    "Exception",
    "Result",
    "Unit",
    "Nothing",
    "Array",
    "List",
    "Map",
    "Set",
    "String",
];

/// Refuse — **loudly, at generation time** — a generated top-level type whose name lands on a
/// per-language reserved list. No silent renaming: the declarer picks another name (D8's spirit,
/// one layer out — a name the tool cannot honour is the declarer's to fix, not the tool's to mangle).
///
/// Scope, honestly: every *declaration-derived* name the generator emits is already suffixed
/// (`<Entity>Snapshot`, `<Value>ErrorFfi`, `…StashFfi`), so a normal declaration is structurally out
/// of collision range — this is a **tripwire for a future generator change** that emits a bare name,
/// not a guard that fires on today's inputs. The per-feature collision surface that *is* live —
/// hand-written custom composite types (`PlainDate`, `AvailabilityRaw`) — is not named by the
/// generator, and reaching it needs a design decision (inspect `custom`'s exports, or bring
/// composite naming into the generator). Recorded in the step-12 report; see `steps/artifacts`.
pub fn reject_reserved_type_names(file: &syn::File) -> syn::Result<()> {
    for item in &file.items {
        let ident = match item {
            syn::Item::Struct(s) => &s.ident,
            syn::Item::Enum(e) => &e.ident,
            _ => continue,
        };
        let name = ident.to_string();
        let lang = if SWIFT_RESERVED.contains(&name.as_str()) {
            Some("Swift")
        } else if KOTLIN_RESERVED.contains(&name.as_str()) {
            Some("Kotlin")
        } else {
            None
        };
        if let Some(lang) = lang {
            return Err(syn::Error::new(
                ident.span(),
                format!(
                    "the generated type `{name}` collides with a {lang} built-in of the same name. \
                     A generated binding must not shadow it — rename the declaration that produces \
                     `{name}` (the tool will not silently rename it for you)."
                ),
            ));
        }
    }
    Ok(())
}

fn emit(feature: &Feature, feature_crate: &str) -> syn::Result<TokenStream2> {
    let fields = field::FieldProj::all(feature);
    let crate_ident = syn::parse_str::<syn::Ident>(feature_crate).map_err(|_| {
        syn::Error::new(
            proc_macro2::Span::call_site(),
            format!("`{feature_crate}` is not a valid crate identifier (BoltFFI rejects hyphens)"),
        )
    })?;

    let checks_exist = !feature.entity.checks().is_empty();
    // Only glob `custom` when a field actually needs it: for `gen-note` the module does not exist,
    // and an unconditional `use crate::custom::*;` would demand an empty one.
    let custom_import = fields.iter().any(|p| p.is_custom()).then(|| {
        quote!(
            use crate::custom::*;
        )
    });
    // `Checked` is only in scope when a check exists: an unused trait import is a warning, and
    // `mise run check` runs clippy with `-D warnings` over the generated file like any other.
    let checked_import = checks_exist.then(|| {
        quote!(
            use ::bolted_core::Checked;
        )
    });
    let core_error_import = checks_exist.then(|| {
        quote!(
            use ::bolted_core::report::ErrorData as CoreErrorData;
        )
    });

    let field_id = dto::field_id_enum(feature);
    let value_errors = feature.values.iter().map(dto::value_error);
    let checker_traits = fields
        .iter()
        .filter(|p| p.field.check.is_some())
        .map(dto::checker_trait);
    let snapshot = dto::snapshot(feature, &fields);
    let values = dto::values(feature, &fields);
    let stash = dto::stash(feature, &fields);
    let report = dto::report(feature);
    let plumbing = wrapper::plumbing(feature, &fields);
    let store_class = wrapper::store_class(feature);
    let draft_class = wrapper::draft_class(feature, &fields);

    let entity_doc = format!(
        " The FFI layer of `{}`, projected from `{feature_crate}`.",
        feature.entity.name
    );
    let _ = suffixed(&feature.entity.name, "Draft"); // named for the reader; used inside `wrapper`

    Ok(quote! {
        #![doc = #entity_doc]
        //!
        //! Generated. Every judgement it appears to make is a call into `bolted-core`.

        // Import order is rustfmt's, not a human's. `prettyplease` drops the blank lines that would
        // group these, `cargo fmt --all --check` then sorts what is left, and the drift check would
        // see a file no `gen:ffi` run had produced. Emitting them pre-sorted keeps the two verbs from
        // rewriting each other.
        #custom_import
        #checked_import
        #core_error_import
        use ::bolted_core::{Draft, DraftId, Stashable, StoreDraft, SubmitError};

        // The shared `#[data]` DTOs. Visible to bindgen only because `bolted_ffi` is a direct
        // dependency that itself depends on boltffi (step 10, M0, row 5).
        use ::bolted_ffi::*;

        use ::#crate_ident::*;
        use boltffi::*;
        use std::collections::BTreeMap;
        use std::sync::{Arc, Mutex, MutexGuard};

        #field_id
        #(#value_errors)*
        #(#checker_traits)*
        #snapshot
        #values
        #stash
        #report
        #plumbing
        #store_class
        #draft_class
    })
}

/// The drift check (D22), shared by every `<feature>-ffi` crate's test.
///
/// Compares the **code**, not the bytes. `mise run check` also runs `cargo fmt --all --check`, so the
/// committed file is rustfmt's, while `generate` emits `prettyplease`'s. Two formatters, one file.
/// Rather than pick a fight between them, both sides are parsed and re-printed through one formatter
/// before comparison, so the check is formatter-agnostic and still sees every change to the code.
///
/// What that leaves uncaught: a hand-added `//` line comment, which no formatter preserves through a
/// parse. A `///` doc comment is an attribute and *is* caught, as is every token of code. The banner
/// is checked separately, and it says DO NOT EDIT.
///
/// Reports the first differing line rather than dumping two thousand of them.
pub fn check_drift(source: &str, feature_crate: &str, committed: &str) -> Result<(), String> {
    let generated = generate(source, feature_crate).map_err(|e| e.to_string())?;
    if !committed.starts_with(BANNER.trim_end()) && !committed.starts_with("// @generated") {
        return Err(format!(
            "`{feature_crate}`'s committed FFI layer has lost its `// @generated` banner. \
             Run `mise run gen:ffi`."
        ));
    }

    let normalise = |src: &str, what: &str| -> Result<String, String> {
        let file =
            syn::parse_file(src).map_err(|e| format!("parsing the {what} FFI layer: {e}"))?;
        Ok(prettyplease::unparse(&file))
    };
    let committed_code = normalise(committed, "committed")?;
    let generated_code = normalise(&generated, "generated")?;
    if committed_code == generated_code {
        return Ok(());
    }

    let (mut want, mut got) = (committed_code.lines(), generated_code.lines());
    let mut line = 0usize;
    loop {
        line += 1;
        match (want.next(), got.next()) {
            (None, None) => break,
            (a, b) if a == b => continue,
            (a, b) => {
                return Err(format!(
                    "`{feature_crate}`'s committed FFI layer drifted from its declaration, \
                     first at line {line}:\n  committed: {}\n  generated: {}\n\n\
                     Run `mise run gen:ffi`, then read the diff before you commit it.",
                    a.unwrap_or("<end of file>"),
                    b.unwrap_or("<end of file>"),
                ));
            }
        }
    }
    Err("the two differ, but no line does — a trailing-newline difference".to_owned())
}
